const prefix = 'Account';

export const UPDATE_ACCOUNT_AVATAR_REQUEST = `${prefix}/UPDATE_ACCOUNT_AVATAR_REQUEST`;
export const UPDATE_ACCOUNT_AVATAR_SUCCESS = `${prefix}/UPDATE_ACCOUNT_AVATAR_SUCCESS`;
export const UPDATE_ACCOUNT_AVATAR_FAILURE = `${prefix}/UPDATE_ACCOUNT_AVATAR_FAILURE`;

export const UPDATE_ACCOUNT_INFO_REQUEST = `${prefix}/UPDATE_ACCOUNT_INFO_REQUEST`;
export const UPDATE_ACCOUNT_INFO_SUCCESS = `${prefix}/UPDATE_ACCOUNT_INFO_SUCCESS`;
export const UPDATE_ACCOUNT_INFO_FAILURE = `${prefix}/UPDATE_ACCOUNT_INFO_FAILURE`;

export const UPDATE_ACCOUNT_PASSWORD_REQUEST = `${prefix}/UPDATE_ACCOUNT_PASSWORD_REQUEST`;
export const UPDATE_ACCOUNT_PASSWORD_SUCCESS = `${prefix}/UPDATE_ACCOUNT_PASSWORD_SUCCESS`;
export const UPDATE_ACCOUNT_PASSWORD_FAILURE = `${prefix}/UDATE_ACCOUNT_PASSWORD_FAILURE`;

export const CONNECT_ACCOUNT_SOCIAL_REQUEST = `${prefix}/CONNECT_ACCOUNT_SOCIAL_REQUEST`;
export const CONNECT_ACCOUNT_SOCIAL_SUCCESS = `${prefix}/CONNECT_ACCOUNT_SOCIAL_SUCCESS`;
export const CONNECT_ACCOUNT_SOCIAL_FAILURE = `${prefix}/CONNECT_ACCOUNT_SOCIAL_FAILURE`;

export const DELETE_ACCOUNT_SOCIAL_REQUEST = `${prefix}/DELETE_ACCOUNT_SOCIAL_REQUEST`;
export const DELETE_ACCOUNT_SOCIAL_SUCCESS = `${prefix}/DELETE_ACCOUNT_SOCIAL_SUCCESS`;
export const DELETE_ACCOUNT_SOCIAL_FAILURE = `${prefix}/DELETE_ACCOUNT_SOCIAL_FAILURE`;

export const GET_AUTOCOMPLETE_REQUEST = `${prefix}/GET_AUTOCOMPLETE_REQUEST`;
export const GET_AUTOCOMPLETE_SUCCESS = `${prefix}/GET_AUTOCOMPLETE_SUCCESS`;
export const GET_AUTOCOMPLETE_FAILURE = `${prefix}/GET_AUTOCOMPLETE_FAILURE`;
