const prefix = 'Auth';

export const SIGN_IN_VIA_SOCIAL_REQUEST = `${prefix}/SIGN_IN_VIA_SOCIAL_REQUEST`;
export const SIGN_IN_VIA_SOCIAL_SUCCESS = `${prefix}/SIGN_IN_VIA_SOCIAL_SUCCESS`;
export const SIGN_IN_VIA_SOCIAL_FAILURE = `${prefix}/SIGN_IN_VIA_SOCIAL_FAILURE`;

export const REGISTRATION_OAUTH_REQUEST = `${prefix}/REGISTRATION_OAUTH_REQUEST`;
export const REGISTRATION_OAUTH_FAILURE = `${prefix}/REGISTRATION_OAUTH_FAILURE`;
export const REGISTRATION_OAUTH_SUCCESS = `${prefix}/REGISTRATION_OAUTH_SUCCESS`;
