const prefix = 'Chat';

export const GET_CHATS_REQUEST = `${prefix}/GET_CHATS_REQUEST`;
export const GET_CHATS_SUCCESS = `${prefix}/GET_CHATS_SUCCESS`;
export const GET_CHATS_FAILURE = `${prefix}/GET_CHATS_FAILURE`;

export const CREATE_CHAT_MESSAGE_REQUEST = `${prefix}/CREATE_CHAT_MESSAGE_REQUEST`;
export const CREATE_CHAT_MESSAGE_SUCCESS = `${prefix}/CREATE_CHAT_MESSAGE_SUCCESS`;
export const CREATE_CHAT_MESSAGE_RECEIVE = `${prefix}/CREATE_CHAT_MESSAGE_RECEIVE`;
export const CREATE_CHAT_MESSAGE_FAILURE = `${prefix}/CREATE_CHAT_MESSAGE_FAILURE`;

export const READ_CHAT_MESSAGE_REQUEST = `${prefix}/READ_CHAT_MESSAGE_REQUEST`;
export const READ_CHAT_MESSAGE_SUCCESS = `${prefix}/READ_CHAT_MESSAGE_SUCCESS`;
export const READ_CHAT_MESSAGE_FAILURE = `${prefix}/READ_CHAT_MESSAGE_FAILURE`;

export const GET_MESSAGES_REQUEST = `${prefix}/GET_MESSAGES_REQUEST`;
export const GET_MESSAGES_SUCCESS = `${prefix}/GET_MESSAGES_SUCCESS`;
export const GET_MESSAGES_FAILURE = `${prefix}/GET_MESSAGES_FAILURE`;

export const CLEAN_ALL_CHATS_REQUEST = `${prefix}/CLEAN_ALL_CHATS_REQUEST`;
export const CLEAN_ALL_CHATS_RECEIVE = `${prefix}/CLEAN_ALL_CHATS_RECEIVE`;
export const CLEAN_ALL_CHATS_FAILURE = `${prefix}/CLEAN_ALL_CHATS_FAILURE`;

export const CLEAR_TEAM_CHAT = `${prefix}/CLEAR_TEAM_CHAT`;
export const CLEAR_TEAM_CHATS = `${prefix}/CLEAR_TEAM_CHATS`;

export const GET_PERSONAL_CHATS_REQUEST = `${prefix}/GET_PERSONAL_CHATS_REQUEST`;
export const GET_PERSONAL_CHATS_SUCCESS = `${prefix}/GET_PERSONAL_CHATS_RECEIVE`;
export const GET_PERSONAL_CHATS_FAILURE = `${prefix}/GET_PERSONAL_CHATS_FAILURE`;

export const CREATE_PERSONAL_CHAT_REQUEST = `${prefix}/CREATE_PERSONAL_CHAT_REQUEST`;
export const CREATE_PERSONAL_CHAT_SUCCESS = `${prefix}/CREATE_PERSONAL_CHAT_SUCCESS`;
export const CREATE_PERSONAL_CHAT_FAILURE = `${prefix}/CREATE_PERSONAL_CHAT_FAILURE`;
export const CREATE_PERSONAL_CHAT_RECEIVE = `${prefix}/CREATE_PERSONAL_CHAT_RECEIVE`;
export const REMOVE_CHAT_RECEIVE = `${prefix}/REMOVE_CHAT_RECEIVE`;

export const SELECT_PERSONAL_CHAT = `${prefix}/SELECT_PERSONAL_CHAT`;

export const LEAVE_USERS_FROM_COURSE_RECEIVE = `${prefix}/LEAVE_USERS_FROM_COURSE_RECEIVE`;
export const JOIN_USERS_IN_COURSE_RECEIVE = `${prefix}/JOIN_USERS_IN_COURSE_RECEIVE`;

export const UPDATE_USER_RECEIVE = `${prefix}/UPDATE_USER_RECEIVE`;

export const LEAVE_CHAT = `${prefix}/LEAVE_CHAT`;

export const GET_USERS_CHATS_REQUEST = `${prefix}/GET_USERS_CHATS_REQUEST`;
export const GET_USERS_CHATS_SUCCESS = `${prefix}/GET_USERS_CHATS_RECEIVE`;
export const GET_USERS_CHATS_FAILURE = `${prefix}/GET_USERS_CHATS_FAILURE`;
